# Generated by Django 3.2.7 on 2021-09-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_card_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Mindfulness', 'Mindfulness'), ('Interpersonal Effectiveness', 'Interpersonal Effectiveness'), ('Emotion Regulation', 'Emotion Regulation'), ('Distress Tolerance', 'Distress Tolerance'), ('Validation', 'Validation')], max_length=100, null=True),
        ),
    ]
