# Generated by Django 3.2.7 on 2021-10-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_card_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='is_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='is_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
