# Generated by Django 3.2.7 on 2021-09-20 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary_card_entities', '0002_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_name', models.CharField(max_length=50, null=True)),
                ('target_description', models.CharField(max_length=1000, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Thoughts/Urges', 'Thoughts/Urges'), ('Emotions/Feelings', 'Emotions/Feelings'), ('Actions/Behaviors', 'Actions/Behaviors')], max_length=100, null=True)),
                ('creator_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('patient_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
