# Generated by Django 3.2.7 on 2021-10-11 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_card_entities', '0003_diaryentry_mood_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='mood_score',
            field=models.PositiveSmallIntegerField(default=6, null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
