# Generated by Django 3.2.7 on 2021-09-28 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary_card_entities', '0004_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('entry_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('sud_score', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(max_length=5000, null=True)),
                ('patient_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryAttribute',
            fields=[
                ('attribute_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('related_attribute_uuid', models.UUIDField(help_text='related entity uuid', null=True)),
                ('type', models.CharField(choices=[('skill', 'skill'), ('target', 'target'), ('emotion', 'emotion')], max_length=40)),
                ('rating', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('diary_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary_card_entities.diaryentry')),
            ],
        ),
    ]
