# Generated by Django 3.2.7 on 2021-10-12 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_card_entities', '0004_alter_diaryentry_mood_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudscore',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
